name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (change as needed)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: crazar374
          output: github-contribution-grid-snake.svg

      - name: Upload Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
