name: Generate Snake Animation

on:
  # Schedule the action to run daily
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (UTC time)
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: CrazAr374
          output: dist/github-contribution-grid-snake.svg

      # Push the generated snake animation back to the repository
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
